FROM shangxian/nginx:2.1-alpine3.9
LABEL maintainer="xuexb <fe.xiaowu@gmail.com>"
LABEL org.opencontainers.image.source https://github.com/xuexb/blog
WORKDIR /etc/nginx/app
COPY --from=xuexb/blog:node-latest /root/app/www /etc/nginx/app
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080