name: clean blog-pr.dev.xuexb.com

on:
  pull_request_target:
    types: [closed]

env:
  DOMAIN: blog-pr-${{ github.event.pull_request.number }}.dev.xuexb.com

jobs:
  clean-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: clean
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            node_container_name="${{ env.DOMAIN }}-node"
            nginx_container_name="${{ env.DOMAIN }}-nginx"
            docker ps -aq --filter "name=$node_container_name" | xargs docker rm -f || echo "Delete fail"
            docker ps -aq --filter "name=$nginx_container_name" | xargs docker rm -f || echo "Delete fail"
            dyups_result=""
            for((i=1;i<=5;i++)); do
              httpcode=$(curl -sL --max-time 5 -w '%{http_code}' -X DELETE "https://dyups.xuexb.com/api/${{ env.DOMAIN }}?r=$RANDOM&token=${{ secrets.DYUPS_TOKEN }}" -o /dev/null)
              if [ "$httpcode" != "200" ]; then
                echo "删除 dyups 失败，响应码：$httpcode ，继续尝试"
                dyups_result="0"
              else
                echo "删除 dyups 成功"
                dyups_result="1"
                break
              fi
            done
            if [ "$dyups_result" == "0" ]; then
              echo "尝试了5次，最终还是失败，我也没办法"
              exit 12
            fi